---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: cdnclasses.cdn.gympass.com
spec:
  group: cdn.gympass.com
  names:
    kind: CDNClass
    listKind: CDNClassList
    plural: cdnclasses
    singular: cdnclass
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CDNClass is the Schema for the cdnclasses API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CDNClassSpec defines the desired state of CDNClass
            properties:
              certificateArn:
                type: string
              hostedZoneID:
                type: string
            required:
            - certificateArn
            - hostedZoneID
            type: object
          status:
            description: CDNClassStatus defines the observed state of CDNClass
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
